### ISSUE TITLE
InitUpload(),总是返回-10002

### ISSUE THREAD

**Issue by uzaidabin** [tencentyun/vod-csharp-server-sdk-v4#1]
错误信息： "canRetry": 0, "code": -10002, "codeDesc": "Checksig svr fail, code ERR_SIG_FAILURE\n","message": "检查签名出错", "sessionInfo": ""
 
//上传调用，根据demo，只修改了id和key
VodCall vodCallUpload = new VodCall();
            vodCallUpload.Init("AKID3uVqvlCfj8ICqFDJxLbeU9bppcBUrKq6", "orqHZfK2ayBC1f6QYVGqGUWxxxxxxx", VodCall.USAGE_UPLOAD);
            vodCallUpload.SetFileInfo(@"D:\temp\video\c程序设计.mp4", "c程序设计", "mp4", 1);
            vodCallUpload.Upload();

**Comment by dodynamiccast** [comment]
已经解决，麻烦重试，不能解决的话麻烦找一下一线人员

**Comment by uzaidabin** [comment]
谢谢
